performing beamline actions

diff --git a/.github/workflows/build_conda_v2.yml b/.github/workflows/build_conda_v2.yml
--- a/.github/workflows/build_conda_v2.yml
+++ b/.github/workflows/build_conda_v2.yml
@@ -14,8 +14,8 @@ jobs:
       fail-fast: false
       matrix:
         os: [ ubuntu-latest ]
-        repos: [{org: "NSLS-II-CSX", repo: "profile_collection", branch: "master", profile_branch: "qserver"},
-                {org: "NSLS-II-SRX", repo: "profile_collection", branch: "master", profile_branch: "master"}]
+        repos: [{org: "NSLS-II-CSX", repo: "profile_collection", branch: "master", profile_branch: "qserver", beamline_acronym: "CSX"},
+                {org: "NSLS-II-SRX", repo: "profile_collection", branch: "master", profile_branch: "master", beamline_acronym: "SRX"}]
         zenoto: [{env: "2023-3.3-py310-tiled", id: "10148425", checksum: "0a47934380db013b36f3e089afdff6aa"}]
     name: Run all repos
     runs-on: ${{ matrix.os }}
@@ -34,36 +34,65 @@ jobs:
           branch: ${{matrix.repos.branch}}
           owner: ${{matrix.repos.org}}
           repository: ${{matrix.repos.repo}}
-      - name: Configuring defaults
+#      - name: Configuring defaults
+#        run: |
+#          echo "pyOlog config:"
+#          wget https://raw.githubusercontent.com/NSLS-II/profile-collection-ci/master/configs/pyOlog.conf -O $HOME/.pyOlog.conf
+#          cat $HOME/.pyOlog.conf
+#
+#          echo "Classic databroker v0/v1 config:"
+#          databroker_conf_dir="$HOME/.config/databroker"
+#          beamline_acronym="${BEAMLINE_ACRONYM,,}"
+#          databroker_bl_conf="${beamline_acronym}.yml"
+#          mkdir -v -p ${databroker_conf_dir}
+#          wget https://raw.githubusercontent.com/NSLS-II/profile-collection-ci/master/configs/databroker.yml -O ${databroker_conf_dir}/_legacy_config.yml
+#          cp -v ${databroker_conf_dir}/_legacy_config.yml ${databroker_conf_dir}/${databroker_bl_conf}
+#          cat ${databroker_conf_dir}/_legacy_config.yml
+#          cat ${databroker_conf_dir}/${databroker_bl_conf}
+#
+#          echo "Tiled profile config:"
+#          tiled_profiles_dir="$HOME/.config/tiled/profiles/"
+#          mkdir -v -p "${tiled_profiles_dir}"
+#          sed 's/^  //' << EOF > "${tiled_profiles_dir}/profiles.yml"
+#          ${beamline_acronym:-local}:
+#            direct:
+#              authentication:
+#                allow_anonymous_access: true
+#              trees:
+#              - tree: databroker.mongo_normalized:Tree.from_uri
+#                path: /
+#                args:
+#                  uri: mongodb://localhost:27017/metadatastore-local
+#                  asset_registry_uri: mongodb://localhost:27017/asset-registry-local
+      - name: Performing Beamline actions
+        env:
+          BEAMLINE_ACRONYM: ${{matrix.repos.beamline_acronym}}
         run: |
-          echo "pyOlog config:"
-          wget https://raw.githubusercontent.com/NSLS-II/profile-collection-ci/master/configs/pyOlog.conf -O $HOME/.pyOlog.conf
-          cat $HOME/.pyOlog.conf
+          echo "Performing beamline-specific tasks..."
+          cfg_dir="/nsls2/data/$BEAMLINE_ACRONYM/shared/config"
+          if [[ ! -d "$cfg_dir" ]]; then
+            mkdir -v -p "$cfg_dir" ||
+            (
+              echo "Error: Couldn't create dir: ${$cfg_dir}"
+              exit 1
+            )
+          fi
+          ;;
 
-          echo "Classic databroker v0/v1 config:"
-          databroker_conf_dir="$HOME/.config/databroker"
-          beamline_acronym="${BEAMLINE_ACRONYM,,}"
-          databroker_bl_conf="${beamline_acronym}.yml"
-          mkdir -v -p ${databroker_conf_dir}
-          wget https://raw.githubusercontent.com/NSLS-II/profile-collection-ci/master/configs/databroker.yml -O ${databroker_conf_dir}/_legacy_config.yml
-          cp -v ${databroker_conf_dir}/_legacy_config.yml ${databroker_conf_dir}/${databroker_bl_conf}
-          cat ${databroker_conf_dir}/_legacy_config.yml
-          cat ${databroker_conf_dir}/${databroker_bl_conf}
-
-          echo "Tiled profile config:"
-          tiled_profiles_dir="$HOME/.config/tiled/profiles/"
-          mkdir -v -p "${tiled_profiles_dir}"
-          sed 's/^  //' << EOF > "${tiled_profiles_dir}/profiles.yml"
-          ${beamline_acronym:-local}:
-            direct:
-              authentication:
-                allow_anonymous_access: true
-              trees:
-              - tree: databroker.mongo_normalized:Tree.from_uri
-                path: /
-                args:
-                  uri: mongodb://localhost:27017/metadatastore-local
-                  asset_registry_uri: mongodb://localhost:27017/asset-registry-local
+#          echo "Performing beamline-specific tasks..."
+#          case "${BEAMLINE_ACRONYM,,}" in
+#          csx)
+#            # Create non-standard directories:
+#            csx_cfg_dir=/nsls2/data/csx/shared/config/
+#            if [[ ! -d "$csx_cfg_dir" ]]; then
+#              mkdir -v -p "$csx_cfg_dir" ||
+#              (
+#                echo "Error: Couldn't create dir: ${csx_cfg_dir}"
+#                exit 1
+#              )
+#            fi
+#            ;;
+#          esac
 #      - name: Setting up Blackhole IOC
 #        env:
 #          CAPROTO_COMMAND: "python -m caproto.ioc_examples.pathological.spoof_beamline"
