performing beamline actions : debugging

diff --git a/.github/workflows/build_conda_v2.yml b/.github/workflows/build_conda_v2.yml
--- a/.github/workflows/build_conda_v2.yml
+++ b/.github/workflows/build_conda_v2.yml
@@ -71,9 +71,9 @@ jobs:
           echo "Performing beamline-specific tasks..."
           cfg_dir="/nsls2/data/$BEAMLINE_ACRONYM/shared/config"
           if [[ ! -d "$cfg_dir" ]]; then
-            mkdir -v -p "$cfg_dir" ||
+            sudo mkdir -v -p "$cfg_dir" ||
             (
-              echo "Error: Couldn't create dir: ${$cfg_dir}"
+              echo "Error: Couldn't create dir: $cfg_dir"
               exit 1
             )
           fi
