FULL TEST

diff --git a/.github/workflows/build_conda_v2.yml b/.github/workflows/build_conda_v2.yml
--- a/.github/workflows/build_conda_v2.yml
+++ b/.github/workflows/build_conda_v2.yml
@@ -81,20 +81,99 @@ jobs:
             sudo mkdir -v -p /etc/bluesky/
             sudo mv -v kafka.yml /etc/bluesky/kafka.yml
             cat /etc/bluesky/kafka.yml
-#      - name: Performing Beamline actions
-#        env:
-#          BEAMLINE_ACRONYM: ${{matrix.repos.beamline_acronym}}
-#        run: |
-#          echo "Performing beamline-specific tasks..."
-#          cfg_dir="/nsls2/data/$BEAMLINE_ACRONYM/shared/config"
-#          if [[ ! -d "$cfg_dir" ]]; then
-#            sudo mkdir -v -p "$cfg_dir" ||
-#            (
-#              echo "Error: Couldn't create dir: $cfg_dir"
-#              exit 1
-#            )
-#          fi
+      - name: Setup Ipython test profile
+        env:
+          PROFILE_REPO: "git@github.com:${{matrix.repos.org}}/${{matrix.repos.repo}}.git"
+          PROFILE_BRANCH: "${{matrix.repos.profile_branch}}"
+          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
+          TEST_PROFILE: "test"
+        run: |
+          eval `ssh-agent`
+          ssh-add - <<< "$SSH_PRIVATE_KEY"
+          echo "Preparing test profile"
+          rm -rfv profile_collection
+            git clone "$PROFILE_REPO" profile_collection
+            (
+              cd profile_collection
+              git checkout "$PROFILE_BRANCH"
+              rm -rfv ~/.ipython/profile_${TEST_PROFILE}/
+              mkdir -pv ~/.ipython/profile_${TEST_PROFILE}/
+              cp -rv startup ~/.ipython/profile_${TEST_PROFILE}/
+            )
+          echo "COMPLETED STARTING UP"
+      - name: Build Conda Env
+        env:
+          CONDA_PREFIX: "home/runner/miniconda"
+          CONDA_ENV_NAME: "2023-3.3-py310-tiled"
+        run: |
+          echo "Installing conda"
+          wget --progress=dot:giga https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
+          bash ./miniconda.sh -b -p $CONDA_PREFIX
+          source "${CONDA_PREFIX}/etc/profile.d/conda.sh"
 
+          echo "Downloading conda env..." &&
+          wget --progress=dot:giga  "https://zenodo.org/record/${{matrix.zenoto.id}}/files/${CONDA_ENV_NAME}.tar.gz?download=1" -O "${CONDA_ENV_NAME}.tar.gz"
+
+          echo "Extracting conda env..."
+          mkdir -v -p "${CONDA_PREFIX}/envs/${CONDA_ENV_NAME}"
+          tar -xvf "${CONDA_ENV_NAME}.tar.gz" -C "${CONDA_PREFIX}/envs/${CONDA_ENV_NAME}"
+          set +u
+          conda activate "${CONDA_PREFIX}/envs/${CONDA_ENV_NAME}"
+          conda unpack && echo "Unpacked successfully!"
+          set -u
+      - name: Activating Redis
+        run: |
+          echo "SUDO: Installing redis"
+          sudo apt-get clean
+          sudo apt-get update
+          sudo apt-get install -y redis
+
+          if ! systemctl is-active --quiet redis-server.service; then
+            echo "SUDO: Starting redis server"
+            sudo systemctl start redis-server.service
+          fi
+          systemctl status redis-server.service --lines 0 --no-pager
+
+          echo "DONE WITH REDIS"
+      - name: Activating Mongo
+        run: |
+          sudo apt-get install gnupg curl
+          curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | \
+             sudo gpg -o /usr/share/keyrings/mongodb-server-4.4.gpg \
+             --dearmor
+          echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-4.4.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
+          sudo apt-get update
+          sudo apt-get install -y mongodb-org
+
+          if ! systemctl is-active --quiet mongod; then
+            echo "SUDO: Starting mongo daemon"
+            sudo systemctl start mongod
+          fi
+          systemctl status mongod.service --lines 0 --no-pager
+          echo "DONE WITH MONGO"
+      - name: Performing Beamline actions
+        env:
+          BEAMLINE_ACRONYM: ${{matrix.repos.beamline_acronym}}
+        run: |
+          echo "Performing beamline-specific tasks..."
+          cfg_dir="/nsls2/data/$BEAMLINE_ACRONYM/shared/config"
+          if [[ ! -d "$cfg_dir" ]]; then
+            sudo mkdir -v -p "$cfg_dir" ||
+            (
+              echo "Error: Couldn't create dir: $cfg_dir"
+              exit 1
+            )
+          fi
+      - name: Setting up Blackhole IOC
+        env:
+          CAPROTO_COMMAND: "python -m caproto.ioc_examples.pathological.spoof_beamline"
+        run: |
+          sudo ln -s /path/to/source /bin/caRepeater
+          sudo python -m caproto.ioc_examples.pathological.spoof_beamline &
+          trap 'kill -SIGINT %1; echo exiting...' EXIT
+          sudo ln -svf caproto-repeater "${CONDA_PREFIX}/bin/caRepeater"
+      - name: Confirm Completion
+        run: echo "DONE"
 #          echo "Performing beamline-specific tasks..."
 #          case "${BEAMLINE_ACRONYM,,}" in
 #          csx)
@@ -109,85 +188,10 @@ jobs:
 #            fi
 #            ;;
 #          esac
-#      - name: Setting up Blackhole IOC
-#        env:
-#          CAPROTO_COMMAND: "python -m caproto.ioc_examples.pathological.spoof_beamline"
-#        run: |
-#          sudo ln -s /path/to/source /bin/caRepeater
-#          sudo python -m caproto.ioc_examples.pathological.spoof_beamline &
-#          trap 'kill -SIGINT %1; echo exiting...' EXIT
-#          sudo ln -svf caproto-repeater "${CONDA_PREFIX}/bin/caRepeater"
 
-#      - name: Setup Ipython test profile
-#        env:
-#          PROFILE_REPO: "git@github.com:${{matrix.repos.org}}/${{matrix.repos.repo}}.git"
-#          PROFILE_BRANCH: "${{matrix.repos.profile_branch}}"
-#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
-#          TEST_PROFILE: "test"
-#        run: |
-#          eval `ssh-agent`
-#          ssh-add - <<< "$SSH_PRIVATE_KEY"
-#          echo "Preparing test profile"
-#          rm -rfv profile_collection
-#            git clone "$PROFILE_REPO" profile_collection
-#            (
-#              cd profile_collection
-#              git checkout "$PROFILE_BRANCH"
-#              rm -rfv ~/.ipython/profile_${TEST_PROFILE}/
-#              mkdir -pv ~/.ipython/profile_${TEST_PROFILE}/
-#              cp -rv startup ~/.ipython/profile_${TEST_PROFILE}/
-#            )
-#          echo "COMPLETED STARTING UP"
-#      - name: Build Conda Env
-#        env:
-#          CONDA_PREFIX: "home/runner/miniconda"
-#          CONDA_ENV_NAME: "2023-3.3-py310-tiled"
-#        run: |
-#          echo "Installing conda"
-#          wget --progress=dot:giga https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
-#          bash ./miniconda.sh -b -p $CONDA_PREFIX
-#          source "${CONDA_PREFIX}/etc/profile.d/conda.sh"
-#
-#          echo "Downloading conda env..." &&
-#          wget --progress=dot:giga  "https://zenodo.org/record/${{matrix.zenoto.id}}/files/${CONDA_ENV_NAME}.tar.gz?download=1" -O "${CONDA_ENV_NAME}.tar.gz"
-#
-#          echo "Extracting conda env..."
-#          mkdir -v -p "${CONDA_PREFIX}/envs/${CONDA_ENV_NAME}"
-#          tar -xvf "${CONDA_ENV_NAME}.tar.gz" -C "${CONDA_PREFIX}/envs/${CONDA_ENV_NAME}"
-#          set +u
-#          conda activate "${CONDA_PREFIX}/envs/${CONDA_ENV_NAME}"
-#          conda unpack && echo "Unpacked successfully!"
-#          set -u
-#      - name: Activating Redis
-#        run: |
-#          echo "SUDO: Installing redis"
-#          sudo apt-get clean
-#          sudo apt-get update
-#          sudo apt-get install -y redis
-#
-#          if ! systemctl is-active --quiet redis-server.service; then
-#            echo "SUDO: Starting redis server"
-#            sudo systemctl start redis-server.service
-#          fi
-#          systemctl status redis-server.service --lines 0 --no-pager
-#
-#          echo "DONE WITH REDIS"
-#      - name: Activating Mongo
-#        run: |
-#          sudo apt-get install gnupg curl
-#          curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc | \
-#             sudo gpg -o /usr/share/keyrings/mongodb-server-4.4.gpg \
-#             --dearmor
-#          echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-4.4.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-4.4.list
-#          sudo apt-get update
-#          sudo apt-get install -y mongodb-org
-#
-#          if ! systemctl is-active --quiet mongod; then
-#            echo "SUDO: Starting mongo daemon"
-#            sudo systemctl start mongod
-#          fi
-#          systemctl status mongod.service --lines 0 --no-pager
-#          echo "DONE WITH MONGO"
+
+
+
 
 #          sudo apt-get update
 #          sudo apt-get install -y lsb-release
